artist_shuffle_security:
    resource: "@ArtistShuffleSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

artist_shuffle_user:
    resource: "@ArtistShuffleUserBundle/Controller/"
    type:     annotation
    prefix:   /

artist_shuffle_artist:
    resource: "@ArtistShuffleArtistBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
