# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    zack:
                        password: $2y$12$vz8bPzU6ipfzPIEEwPFttes75sFCUS63A35nirrackKjTRP6.O1oK
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$M7YqkjAr0.yRLypnr.ZGbeq5V8MraDsYuRVnrPZAkp.9Hhh26lKRK
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/users, roles: ROLE_ADMIN }
        - { path: ^/artist, roles: ROLE_ADMIN }
        - { path: ^/genres, roles: ROLE_ADMIN }