<?php

namespace ArtistShuffle\ArtistBundle\Entity;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll( $user_id = null )
    {
        if ( $user_id )
        {
            return $this->findBy(array('user' => $user_id), array('name' => 'ASC'));
        }
        else
        {
            return $this->findBy(array(), array('name' => 'ASC'));
        }
    }
}
